name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: utils_test
          POSTGRES_USER: utils
          POSTGRES_PASSWORD: password
    strategy:
      matrix:
        include:
          - python_version: "3.6"
          - python_version: "3.8"
          - python_version: "3.9"
          - python_version: "3.10"
          - python_version: "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: utils_test
          POSTGRES_USER: utils
          POSTGRES_PASSWORD: password
        run: |
          cd src
          ./manage.py test
